export const sidenav = {
  OPEN_SIDENAV: "OPEN_SIDENAV",
  CLOSE_SIDENAV: "CLOSE_SIDENAV",
  TOGGLE_SIDENAV: "TOGGLE_SIDENAV"
};

export const professors = {
  FETCH_PROFESSORS: "FETCH_PROFESSORS",
  FETCH_PROFESSORS_PENDING: "FETCH_PROFESSORS_PENDING",
  FETCH_PROFESSORS_FULLFILED: "FETCH_PROFESSORS_FULFILLED",
  FETCH_PROFESSORS_REJECTED: "FETCH_PROFESSORS_REJECTED"
};
